# Generated by Django 3.0.6 on 2021-01-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0009_auto_20201216_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
